### Register a new user
POST http://localhost:8080/api/user/userreg
Content-Type: application/json

{
  "username": "user6",
  "password": "1234",
  "name": "정호현",
  "email": "asdf@naver.com",
  "birthDate": "2024-12-12",
  "registrationDate": "2024-12-12T12:00:00"
}

### Login request
POST http://localhost:8080/api/user/login
Content-Type: application/x-www-form-urlencoded

username=user6&password=1234

### userList request
GET http://localhost:8080/api/user/userList
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyNiIsImlhdCI6MTcyMjQ0MDUwMCwiZXhwIjoxNzIyNDQ3NzAwfQ.d--r33S5BvToNkrOnfEBMDTnGQie9mup92TA3VlsOPA
